<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2ade8d5c-f115-4e7f-8107-839d1851bfc0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_docs_intro</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/docs\/intro']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navbar__item navbar__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navbar__item navbar__link</value>
        <webElementGuid>ea04769e-83f7-46d7-890b-fdf33399d190</webElementGuid>
    </webElementProperties>
</WebElementEntity>