<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>618c5ce9-7ce3-4a06-8dab-646aafdb039f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_docs_intro</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/docs\/intro']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navbar__item navbar__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navbar__item navbar__link</value>
        <webElementGuid>9f8eb45f-6fbd-4004-9440-27b3af14a6c5</webElementGuid>
    </webElementProperties>
</WebElementEntity>